
services:
  auth_service:
    build: ./
    environment:
      DEBUG: "true"
      DEBUG_PORT: 8001
      # Переменные подключения к БД и Redis, например:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8001:8001"
      - "8081:8081"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: hw5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: schef2002
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
